### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Briiqn** [Sxnpaiwin/IgotAFellingproblemsiklol#4]
Hey, I just updated the playit only branch workflow configuration (blank.yml) It should fix all issues you are facing with uptime issues and errors (was fixed in main a long time ago but never fixed in playit-only)
The fix will require you to rename your main branch to playit-only (or just update your fork of the repository and run the CI workflow for playit-only now. Your welcome

https://github.com/Briiqn/Actions-Server/blob/playit-only/.github/workflows/blank.yml

**Comment by Sxnpaiwin** [comment]
Thanks Very much
